/* Axel settings, generated by configure */
#define _REENTRANT
#define _THREAD_SAFE
#define ETCDIR "/home/chenlin/server_ui/axel-2.4/axellib//etc"
#define LOCALE "/home/chenlin/server_ui/axel-2.4/axellib//share/locale"
#define ARCH "Darwin"

#define NOGETOPTLONG
#define DARWIN
